### ISSUE TITLE
Python Interface

### ISSUE THREAD

**Issue by tkloczko** [corese-stack/corese-core#1]
## Summary

À partir du notebook de base, mettre en place une interface python basée sur Corese-Core qui respecte les usages du monde python et qui ne soit pas un simple wrapping de classes java.

## Tasks

- [x] choose the Java-Python bridge package to support (py4j is choosen, jpypy bridge is provided as experimental with no support)
- [x] create a new repo for PyCorese (use the same name?) in corese-stack (pycorese for the moment)
- [x] wrap corese-core classes in Python (for the updated corese-core library)
- [x]  define the high-level interface that supports at least the methods below: Return should be either DtaaFrame or another iterable object modeled on the output formats of SPARQLWrapper package for compatibility. 
    - [x] load data and schema
    - [x] select an inference rule engine (RDFS, OWL...)
    - [x] query loaded data with SELECT and ASK
    - [x] CONSTRUCT query from loaded data
    - [x] validating graph with SHACL
- [ ] etc
