### ISSUE TITLE
Reorganisation des repos git

### ISSUE THREAD

**Issue by tkloczko** [corese-stack/corese-core#2]
## Summary

On veut séparer le repo git original en plusieurs repos pour permettre une plus grande flexibilité. On veut conserver l'historique git.

## Tasks

- [x] #6
- [x] nouveaux repos:
     - [x] `corese-gui`
     - [x] `corese-command`
     - [x] `corese-python`
     - [x]  `corese-server` (qui contient server et docker)
     - [x] `corese-jena`
     - [x] `corese-rdf4j`
     - [x] `corese-W3C` (qui contient les tests de standardization du W3C)
- [x] Update repository description
- [x] README.md
- [x] CHANGES.md
