### ISSUE TITLE
Fabrique des test w3c

### ISSUE THREAD

**Issue by tkloczko** [corese-stack/corese-core#3]
## Summary

On veut refactorer et étendre les tests W3C.

## Tasks

- [ ] Revue de code sur le code java qui génère les tests
- [ ] Identifier tous les standards utilisés dans `corese` et sur lesquels on peut passer des tests W3C
- [ ] Étendre les types de tests
    - Etendre à tous les types visibles 
        - [ ] RDF/SPARQL https://w3c.github.io/rdf-tests/, 
        - [ ] SHACL https://w3c.github.io/data-shapes/data-shapes-test-suite/#Corese, 
        - [ ] JSON-LD https://json-ld.github.io/json-ld.org/test-suite/reports/, 
        - [ ] LDP https://w3c.github.io/ldp-testsuite/,
        - [ ] RDFStar https://w3c.github.io/rdf-tests/rdf/rdf12/ 
- [ ] Avoir un rapport automatique de l'état des tests (OK, KO)
