### ISSUE TITLE
Dive into Corese

### ISSUE THREAD

**Issue by tkloczko** [corese-stack/corese-core#5]
## Summary

En profiter pour regarder comment sont organisés le code et les structures de données.

## Tasks

- [x] Reviewer les DataType de Corese
- [x] Avoir une idée de l'architecture des classes pour le stockage du graphe RDF et des entailments
- [x] Lister les fonctionnalités de Corese (rdfS, owl, transfo de requêtes en algorithmes, parcours de graphe)
- [ ] Détecter les possibles doublons, code smell, etc
